// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnP53_7qqAOLb2c745sFI2AV4WwsWifWE',
    appId: '1:854882412724:web:3d1212f42d3fac0d1dcfe1',
    messagingSenderId: '854882412724',
    projectId: 'deliverypro-a6e3e',
    authDomain: 'deliverypro-a6e3e.firebaseapp.com',
    storageBucket: 'deliverypro-a6e3e.appspot.com',
    measurementId: 'G-NE5B8GRJ8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkMN60n5FkIe1j57VCqg9Qc64tXgSmZdI',
    appId: '1:854882412724:android:3c3423d035a415131dcfe1',
    messagingSenderId: '854882412724',
    projectId: 'deliverypro-a6e3e',
    storageBucket: 'deliverypro-a6e3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj0Xr3_BNykywKopaOhmC9pcqqlEqqWY0',
    appId: '1:854882412724:ios:b5a1da07d555173a1dcfe1',
    messagingSenderId: '854882412724',
    projectId: 'deliverypro-a6e3e',
    storageBucket: 'deliverypro-a6e3e.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj0Xr3_BNykywKopaOhmC9pcqqlEqqWY0',
    appId: '1:854882412724:ios:b5a1da07d555173a1dcfe1',
    messagingSenderId: '854882412724',
    projectId: 'deliverypro-a6e3e',
    storageBucket: 'deliverypro-a6e3e.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnP53_7qqAOLb2c745sFI2AV4WwsWifWE',
    appId: '1:854882412724:web:93e405d13a4d2ad71dcfe1',
    messagingSenderId: '854882412724',
    projectId: 'deliverypro-a6e3e',
    authDomain: 'deliverypro-a6e3e.firebaseapp.com',
    storageBucket: 'deliverypro-a6e3e.appspot.com',
    measurementId: 'G-NBJY0ZRYRL',
  );
}
